=== RafaPC/NetJudias/HTML5/XML/public_html/Biblioteca.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    <xs:element name="biblioteca">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="usuarios">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="usuario">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="numLibros" type="xs:Integer"/>
                                        <xs:element name="libro" maxOccurs="3">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="isb" type="xs:string"/>
                                                    <xs:element name="titulo" type="xs:string"/>
                                                    <xs:element name="autor" type="xs:string"/>
                                                    <xs:element name="numpaginas" type="xs:int"/>
                                                    <xs:element name="prestado" type="xs:boolean"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="libros">
                    <xs:complexType>
                        <xs:element name="libro" maxOccurs="unBounded">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="isb" type="xs:string"/>
                                    <xs:element name="titulo" type="xs:string"/>
                                    <xs:element name="autor" type="xs:string"/>
                                    <xs:element name="numpaginas" type="int"/>
                                    <xs:element name="prestado" type="boolean"/>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RafaPC/NetJudias/HTML5/XML/public_html/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<biblioteca
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Biblioteca.xsd'>
    <usuarios>
        <usuario>
            <nombre>Kiko</nombre>
            <numLibros>1</numLibros>
            <libro>
                <isb>KJHG9765</isb>
                <titulo>Iliada</titulo>
                <autor>Homero Simpson</autor>
                <numpaginas>567</numpaginas>
                <prestado>true</prestado>
            </libro>
        </usuario>
    </usuarios>
    <libros>
        <libro>
            <isb>KJHG9765</isb>
            <titulo>Iliada</titulo>
            <autor>Homero Simpson</autor>
            <numpaginas>567</numpaginas>
            <prestado>true</prestado>
        </libro>
        <libro>
            <isb>OIUY541</isb>
            <titulo>Titulo1</titulo>
            <autor>Autor1</autor>
            <numpaginas>999</numpaginas>
            <prestado>false</prestado>
        </libro>
    </libros>

</biblioteca>
