=== RafaPC/NetJudias/HTML5/XML/public_html/Merchadona.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="merchadona">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="empleados">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="reponedor" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="id" type="xs:integer"/>
                                        <xs:element name="numproductosrepuestos" type="xs:integer"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="cajero" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="id" type="xs:integer"/>
                                        <xs:element name="preciototal" type="xs:double"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="productos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="producto" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="preciobase" type="xs:float"/>
                                        <xs:element name="cantidad" type="xs:integer"/>
                                        <xs:element name="nombre" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="perecedero" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="preciobase" type="xs:float"/>
                                        <xs:element name="cantidad" type="xs:integer"/>
                                        <xs:element name="nombre" type="xs:string"/>
                                        <xs:element name="preciocaducado" type="xs:double"/>
                                        <xs:element name="fechareposicion" type="xs:date"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
        
    </xs:element>
</xs:schema>

=== RafaPC/NetJudias/HTML5/XML/public_html/Merchadona.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<merchadona
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Merchadona.xsd'>
    <empleados>
        <reponedor>
            <nombre>juani</nombre>
            <id>2784</id>
            <numproductosrepuestos>18</numproductosrepuestos>
        </reponedor>
        <cajero>
            <nombre>choni</nombre>
            <id>2773</id>
            <preciototal>304.6</preciototal>
        </cajero>
    </empleados>
    <productos>
        <producto>
            <preciobase>7</preciobase>
            <cantidad>20</cantidad>
            <nombre>celof√°n</nombre>
        </producto>
        <perecedero>
            <preciobase>7</preciobase>
            <cantidad>20</cantidad>
            <nombre>pan bimbo</nombre>
            <preciocaducado>7</preciocaducado>
            <fechareposicion>2002-09-24</fechareposicion>
        </perecedero>
    </productos>
</merchadona>
