=== RafaPC/NetJudias/HTML5/XML/public_html/Polideportivo.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">

    
    <xs:element name="polideportivo">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="actividades">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="actividad">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="tipo" type="xs:string"/>
                                        <xs:element name="plazaslibres" type="xs:Integer"/>
                                        <xs:element name="plazas" type="xs:Integer"/>
                                        <xs:element name="precio" type="xs:float"/>
                                        <xs:element name="alumno">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="nombre" type="xs:string"/>
                                                    <xs:element name="apellidos" type="xs:string"/>
                                                    <xs:element name="pago" type="xs:float"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="horario">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="dias" type="xs:string"/>
                                                    <xs:element name="horacomienzo" type="xs:Integer"/>
                                                    <xs:element name="horafinal" type="xs:Integer"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="alumno">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="nombre" type="xs:string"/>
                            <xs:element name="apellidos" type="xs:string"/>
                            <xs:element name="pago" type="xs:float"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RafaPC/NetJudias/HTML5/XML/public_html/Polideportivo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<polideportivo
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Polideportivo.xsd'>
    <actividades>
        <actividad>
            <tipo>yoga</tipo>
            <plazaslibres>20</plazaslibres>
            <plazas>25</plazas>
            <precio>25.70</precio>
            <alumno>
                <nombre>Alejandro</nombre>
                <apellidos>Folgueras</apellidos>
                <pago>57.80</pago>
            </alumno>
            <horario>
                <dias>L,X,V</dias>
                <horacomienzo>17</horacomienzo>
                <horafinal>19</horafinal>
            </horario>
        </actividad>
    </actividades>
    <alumno>
        <nombre>Jesucristo</nombre>
        <apellidos>SuperStar</apellidos>
        <pago>100</pago>
    </alumno>

</polideportivo>
