=== RafaPC/NetJudias/HTML5/XML/public_html/Zanalcar.xsd
<?xml version="1.0"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<xs:schema version="1.0"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
    <xs:element name="zanalcar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="vehiculos">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="vehiculo">
                                <xs:element name="marca"/>
                                <xs:element name="color"/>
                                <xs:element name="preciodeventa"/>
                                <xs:element name="preciodecompra"/>
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="coche">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="matricula" type="xs:String"/>
                                                    <xs:element name="km" type="xs:Integer"/>
                                                    <xs:element name="preciocompra" type="xs:double"/>
                                                    <xs:element name="precioventa" type="xs:double"/>
                                                    <xs:element name="color" type="xs:String"/>
                                                    <xs:element name="marca" type="xs:String"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="moto">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="matricula" type="xs:String"/>
                                                    <xs:element name="km" type="xs:Integer"/>
                                                    <xs:element name="preciocompra" type="xs:double"/>
                                                    <xs:element name="precioventa" type="xs:double"/>
                                                    <xs:element name="color" type="xs:String"/>
                                                    <xs:element name="marca" type="xs:String"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="quad">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="matricula" type="xs:String"/>
                                                    <xs:element name="km" type="xs:Integer"/>
                                                    <xs:element name="preciocompra" type="xs:double"/>
                                                    <xs:element name="precioventa" type="xs:double"/>
                                                    <xs:element name="color" type="xs:String"/>
                                                    <xs:element name="marca" type="xs:String"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="bici">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="preciocompra" type="xs:double"/>
                                                    <xs:element name="precioventa" type="xs:double"/>
                                                    <xs:element name="tamaÃ±oderueda" type="xs:Integer"/>
                                                    <xs:element name="numdemarchas" type="xs:Integer"/>
                                                    <xs:element name="color" type="xs:String"/>
                                                    <xs:element name="marca" type="xs:String"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType> 
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== RafaPC/NetJudias/HTML5/XML/public_html/Zanalcar.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->


<zanalcar
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xsi:noNamespaceSchemaLocation='Zanalcar.xsd'>
    <vehiculos>
        <coche>
            <matricula>IUYG87654</matricula>
            <km>1</km>
            <preciocompra>1</preciocompra>
            <precioventa>2</precioventa>
            <color>amarillo</color>
            <marca>seat</marca>
        </coche>
        <coche>
            <matricula>2EQWE2</matricula>
            <km>2</km>
            <preciocompra>3</preciocompra>
            <precioventa>4</precioventa>
            <color>verde</color>
            <marca>leon</marca>
        </coche>
        <moto>
            <matricula>DRTGYSE45</matricula>
            <km>3</km>
            <preciocompra>5</preciocompra>
            <precioventa>6</precioventa>
            <color>rojo</color>
            <marca>bmw</marca>
        </moto>
        <moto>
            <matricula>ASER1243</matricula>
            <km>4</km>
            <preciocompra>7</preciocompra>
            <precioventa>8</precioventa>
            <color>azul</color>
            <marca>mercedes</marca>
        </moto>
        <quad>
            <matricula>ADRTQ34</matricula>
            <km>5</km>
            <preciocompra>9</preciocompra>
            <precioventa>10</precioventa>
            <color>gris</color>
            <marca>tesla</marca>
        </quad>
        <quad>
            <matricula>AEWT7563</matricula>
            <km>6</km>
            <preciocompra>11</preciocompra>
            <precioventa>12</precioventa>
            <color>morado</color>
            <marca>lexus</marca>
        </quad>
        <bici>
            <preciocompra>13</preciocompra>
            <precioventa>14</precioventa>
            <tama単oderueda>10</tama単oderueda>
            <numdemarchas>21</numdemarchas>
            <tipodecambio>automatico</tipodecambio>
            <color>verde</color>
            <marca>elbicho</marca>
        </bici>
        <bici>
            <preciocompra>15</preciocompra>
            <precioventa>16</precioventa>
            <tama単oderueda>10</tama単oderueda>
            <numdemarchas>18</numdemarchas>
            <tipodecambio>manual</tipodecambio>
            <color>verde</color>
            <marca>blabla</marca>
        </bici>
    </vehiculos>

</zanalcar>
